name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

# 关键步骤 1: 为 Actions 授予推送到 GitHub Packages 的权限
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 关键步骤 2: 登录到 GitHub Container Registry
      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 关键步骤 3: 构建并推送镜像，注意 tags 格式的变化
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/transbridge:latest
